version: 2
updates:
  - package-ecosystem: pip-compile
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: GMT
    open-pull-requests-limit: 50
    target-branch: main
