version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
        environment:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/circle_test?sslmode=disable
          ENV: testing
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - restore_cache:
          key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
      - python/install-packages:
          pip-dependency-file: requirements.dev.txt
          pkg-manager: pip
      - save_cache:
          key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - /home/circleci/.local/share/virtualenvs
            - /home/circleci/.cache/pip
      - run:
          name: Run tests
          environment:
            SECRET_KEY: "django-insecure-circleci-testing"
          command: |
            mkdir test-results
            pipenv run pytest --junitxml=test-results/junit.xml
      - run:
          name: Collect Statics
          command: ./manage.py collectstatic --noinput
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
