# Generated by Django 5.1.2 on 2024-11-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerberus', '0079_alter_charge_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcharge',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='cerberus.booking'),
        ),
    ]
