# Generated by Django 5.1.2 on 2024-11-14 20:24

import datetime
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import re
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerberus", "0080_alter_bookingcharge_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("interval", models.PositiveIntegerField(default=1)),
                (
                    "days_of_week",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d+(?:,\\d+)*\\Z"),
                                code="invalid",
                                message="Enter only digits separated by commas.",
                            )
                        ],
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(null=True)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("GBP", "GBP £")],
                        default="GBP",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cost",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=14
                    ),
                ),
                (
                    "cost_per_additional_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("GBP", "GBP £")],
                        default="GBP",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "cost_per_additional",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "pets",
                    models.ManyToManyField(
                        related_name="bookingschedules", to="cerberus.pet"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookingschedules",
                        to="cerberus.service",
                    ),
                ),
            ],
        ),
    ]
