# Generated by Django 5.1.2 on 2024-11-18 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerberus", "0081_bookingschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="cerberus.bookingschedule",
            ),
        ),
        migrations.AlterField(
            model_name="bookingschedule",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
