# Generated by Django 5.1.2 on 2024-11-18 21:26

from django.db import migrations

def migrate_enquiry_state_to_preliminary(apps, schema_editor):
    Booking = apps.get_model("cerberus", "Booking")
    for booking in Booking.objects.filter(state="enquiry"):
        booking.state = "preliminary"
        booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ("cerberus", "0082_booking_schedule_alter_bookingschedule_end_date"),
    ]

    operations = [
        migrations.RunPython(migrate_enquiry_state_to_preliminary),
    ]
