name: Update Changelog
on:
  push:
    branches:
      - main
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs(changelog): update changelog"
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main