name: Update Changelog
on:
  push:
    branches:
      - master
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Changelog
        run: |
          python3 -m pip install Commitizen
          cz changelog
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main
